export type Category = 1 | 2 | 3;

export type Word = {
  en: string;
  el: string;
  sent: string;
};

export type CategorizedWord = Word & { cat: Category };

/** Κατηγορία 1 — Έντονα (3 ασκήσεις ανά λέξη) */
export const CAT1: Word[] = [
  { en: "accusation", el: "κατηγορία", sent: "He ceased to make accusation against others." },
  { en: "allied", el: "συμμαχικός", sent: "His thought is allied with power." },
  { en: "Aspirations", el: "φιλοδοξίες", sent: "He falls to the level of his cherished Aspirations." },
  { en: "assured", el: "βέβαιος", sent: "Success is assured when you control your thoughts." },
  { en: "attainment", el: "επίτευξη", sent: "This is the pathway to attainment." },
  { en: "Attendant", el: "συνοδός", sent: "Vice and its attendant sufferings." },
  { en: "Bid", el: "διατάζω", sent: "He bids the tyrant Circumstance to uncrown." },
  { en: "bind down", el: "καθηλώνω", sent: "No hard fate shall bind you down." },
  { en: "Bliss", el: "ευδαιμονία", sent: "He learns both by suffering and bliss." },
  { en: "Blossom", el: "άνθος", sent: "Act is the blossom of thought." },
  { en: "Bring forth", el: "παράγω", sent: "The mind will bring forth fruit." },
  { en: "Cherished", el: "πολυαγαπημένος", sent: "Long-cherished thoughts shape character." },
  { en: "circumstances", el: "περιστάσεις", sent: "Man is buffeted by circumstances." },
  { en: "Command", el: "εντολή", sent: "At the command of glad thoughts." },
  { en: "Compassion", el: "συμπόνια", sent: "A perfect Compassion embraces both." },
  { en: "Comprehensive", el: "ολοκληρωμένος", sent: "The aphorism is so comprehensive." },
  { en: "confined", el: "περιορισμένος", sent: "Confined in a self-made prison." },
  { en: "continually", el: "συνεχώς", sent: "Continually revolting against effect." },
  { en: "Cords", el: "σχοινιά", sent: "He holds the cords of responsibility." },
  { en: "Corn", el: "καλαμπόκι", sent: "Nothing can come from corn but corn." },
  { en: "corruption", el: "διαφθορά", sent: "Righteousness, not corruption, is the force." },
  { en: "Crooked", el: "στραβός", sent: "He adopts crooked measures." },
  { en: "cynicism", el: "κυνισμός", sent: "To live in cynicism is to be confined." },
  { en: "decay", el: "φθορά", sent: "The body sinks into decay." },
  { en: "Deceive", el: "εξαπατώ", sent: "He tries to deceive his employer." },
  { en: "Deceptive", el: "παραπλανητικός", sent: "Indolent, deceptive thoughts." },
  { en: "Declare", el: "δηλώνω", sent: "He can know and declare his sufferings." },
  { en: "Defect", el: "ελάττωμα", sent: "Remedy the defects in his character." },
  { en: "delicate", el: "ευαίσθητος", sent: "The body is a delicate instrument." },
  { en: "Demoralizes", el: "αποθαρρύνει", sent: "Anxiety demoralizes the whole body." },
  { en: "despise", el: "περιφρονώ", sent: "Let us despise the slaves." },
  { en: "destruction", el: "καταστροφή", sent: "Where loss of equipoise would mean total destruction." },
  { en: "Discontent", el: "δυσαρέσκεια", sent: "Passion and discontent mar the face." },
  { en: "Element", el: "στοιχείο", sent: "Thought is an element in life." },
  { en: "Endeavor", el: "προσπάθεια", sent: "A strong and high endeavor." },
  { en: "envy", el: "φθόνος", sent: "Thoughts of envy rob the body." },
  { en: "exert", el: "καταβάλλω", sent: "He begins to exert himself." },
  { en: "Exquisite", el: "εξαίσιος", sent: "Exquisite poise of character." },
  { en: "Foster", el: "καλλιεργώ", sent: "Foster good thoughts." },
  { en: "Fostered", el: "καλλιεργημένος", sent: "The criminal thought had been secretly fostered." },
  { en: "goodwill", el: "καλή θέληση", sent: "Goodwill is a great comforter." },
  { en: "Governed by", el: "διέπεται από", sent: "All achievements are governed by the same law." },
  { en: "Grace", el: "χάρη", sent: "Thoughts crystallize into habits of grace." },
  { en: "grave", el: "σοβαρός", sent: "A grave responsibility." },
  { en: "Grief", el: "θλίψη", sent: "Humanity is tumultuous with grief." },
  { en: "grieve", el: "θρηνώ", sent: "He ceases to fuss and grieve." },
  { en: "guard", el: "προστατεύω", sent: "Guard your mind." },
  { en: "Harbors", el: "φιλοξενεί", sent: "He harbors grovelling thoughts." },
  { en: "Harvest", el: "συγκομιδή", sent: "Man reaps his own harvest." },
  { en: "Hateful", el: "μισητός", sent: "Hateful thoughts crystallize into violence." },
  { en: "heavenly", el: "ουράνιος", sent: "Heavenly environment." },
  { en: "impure", el: "ακάθαρτος", sent: "Impure thoughts shatter the nerves." },
  { en: "Indefinitely", el: "επ' αόριστον", sent: "Cases could be varied indefinitely." },
  { en: "Indispensable", el: "απαραίτητος", sent: "Indispensable to his development." },
  { en: "intellectual", el: "διανοητικός", sent: "Intellectual achievements." },
  { en: "Justly", el: "δίκαια", sent: "His life is justly ordered." },
  { en: "Likewise", el: "ομοίως", sent: "The dishonest man likewise garners." },
  { en: "Linked with", el: "συνδεδεμένος με", sent: "Thought linked with purpose." },
  { en: "mere", el: "απλός", sent: "Mere external facts." },
  { en: "Merely", el: "απλώς", sent: "Merely as illustrative." },
  { en: "Noble", el: "ευγενής", sent: "Strong and noble thoughts." },
  { en: "Obnoxious", el: "ενοχλητικός", sent: "Obnoxious vices." },
  { en: "Occurrence", el: "περιστατικό", sent: "Every trivial occurrence." },
  { en: "pathway", el: "μονοπάτι", sent: "Pathway to attainment." },
  { en: "perceive", el: "αντιλαμβάνομαι", sent: "Perceives the action of law." },
  { en: "Persistent", el: "επίμονος", sent: "A painful and persistent disease." },
  { en: "Persisting", el: "επιμένων", sent: "Persisting in good thoughts." },
  { en: "portion", el: "μερίδιο", sent: "A portion must be sacrificed." },
  { en: "Prematurely", el: "πρόωρα", sent: "Fruit which does not fall prematurely." },
  { en: "prophet", el: "προφήτης", sent: "Composer, sculptor, poet, prophet." },
  { en: "Prosperity", el: "ευημερία", sent: "True prosperity is abiding." },
  { en: "Prosperous", el: "ευημερών", sent: "A happy and prosperous being." },
  { en: "purpose", el: "σκοπός", sent: "A legitimate purpose in his heart." },
  { en: "readily", el: "πρόθυμα", sent: "The body responds readily." },
  { en: "Remedy", el: "θεραπεία", sent: "Calls aloud for remedy." },
  { en: "rigorously", el: "αυστηρά", sent: "Doubts should be rigorously excluded." },
  { en: "rob", el: "ληστεύω", sent: "Sour thoughts rob the body." },
  { en: "royal", el: "βασιλικός", sent: "This is the royal road." },
  { en: "sacrifice", el: "θυσία", sent: "No progress without sacrifice." },
  { en: "sculpture", el: "γλυπτική", sent: "Composer, sculpture, painter." },
  { en: "sensations", el: "αισθήσεις", sent: "Fluctuating sensations." },
  { en: "serenity", el: "γαλήνη", sent: "Serenity is the last lesson." },
  { en: "servant", el: "υπηρέτης", sent: "The body is the servant of the mind." },
  { en: "shatter", el: "συντρίβω", sent: "Will soon shatter the nervous system." },
  { en: "Sinks into", el: "βυθίζεται σε", sent: "The body sinks into disease." },
  { en: "Slaves", el: "σκλάβοι", sent: "Many men are slaves." },
  { en: "sorrow", el: "λύπη", sent: "Dispersing the shadows of sorrow." },
  { en: "sour", el: "ξινός", sent: "A sour face does not come by chance." },
  { en: "Spring up", el: "ξεπηδώ", sent: "Opportunities will spring up." },
  { en: "steer", el: "κατευθύνω", sent: "Steer clear of catastrophe." },
  { en: "Steers", el: "κατευθύνει", sent: "He steers his life." },
  { en: "Stubbornly", el: "πεισματικά", sent: "It stubbornly retards efforts." },
  { en: "suspicion", el: "υποψία", sent: "Thoughts of suspicion." },
  { en: "Tranquil", el: "ήρεμος", sent: "A tranquil heart." },
  { en: "Unlawful", el: "παράνομος", sent: "At the bidding of unlawful thoughts." },
  { en: "Vanity", el: "ματαιοδοξία", sent: "Pleasing to human vanity." },
  { en: "Vastly", el: "κατά πολύ", sent: "Conditions vary vastly." },
  { en: "Vice", el: "βίτσιο", sent: "Aimlessness is a vice." },
  { en: "Vicious", el: "μοχθηρός", sent: "The greedy, dishonest, vicious." },
  { en: "Vigor", el: "σφρίγος", sent: "Body in vigor and grace." },
  { en: "Virtue", el: "αρετή", sent: "Ascending into virtue." },
  { en: "wander", el: "περιπλανιέμαι", sent: "Shall wander to the city." },
  { en: "Weed", el: "ζιζάνιο", sent: "Weed out wrong thoughts." },
  { en: "whine", el: "γκρινιάζω", sent: "Ceases to whine and revile." },
  { en: "Wrinkle", el: "ρυτίδα", sent: "Wrinkle that mars." },
];

/** Κατηγορία 2 — Μεσαία (2 ασκήσεις ανά λέξη) */
export const CAT2: Word[] = [
  { en: "abounding", el: "άφθονος", sent: "Abounding peace." },
  { en: "aimlessness", el: "έλλειψη σκοπού", sent: "Aimlessness is a vice." },
  { en: "Apprehension", el: "ανησυχία", sent: "Apprehension of a great purpose." },
  { en: "arduous", el: "επίπονος", sent: "Long and arduous journey." },
  { en: "Artefact", el: "τέχνημα", sent: "Man is not a creation by artifice." },
  { en: "beautify", el: "ωραιοποιώ", sent: "Beautify your mind." },
  { en: "Bidding of", el: "κατ' εντολήν", sent: "At the bidding of unlawful thoughts." },
  { en: "Buffeted", el: "ταλαιπωρημένος", sent: "Man is buffeted by circumstances." },
  { en: "Cease for", el: "παύει για", sent: "Suffering ceases for him who is pure." },
  { en: "comforter", el: "παρηγορητής", sent: "No comforter to compare with goodwill." },
  { en: "commenced", el: "ξεκίνησε", sent: "Not having commenced to control." },
  { en: "concurred", el: "συμφώνησε", sent: "All concurred in the truth." },
  { en: "contours", el: "περιγράμματα", sent: "Carved into inharmonious contours." },
  { en: "Copernicus", el: "Κοπέρνικος", sent: "Copernicus fostered the vision." },
  { en: "creeping in", el: "εισχωρεί", sent: "Doubt and fear creeping in." },
  { en: "Crucifixion", el: "σταύρωση", sent: "Self-crucifixion leads to success." },
  { en: "crystallizes into", el: "κρυσταλλώνεται σε", sent: "Thought crystallizes into habit." },
  { en: "deathbed", el: "επιθανάτιο κρεβάτι", sent: "Philosopher on his deathbed." },
  { en: "disintegrating", el: "αποσυντιθέμενος", sent: "Disintegrating elements." },
  { en: "dispersing", el: "διασκορπίζοντας", sent: "Dispersing the shadows of grief." },
  { en: "disposition", el: "διάθεση", sent: "Sweet and sunny disposition." },
  { en: "dissipating", el: "διαλύοντας", sent: "Dissipating the ills of the body." },
  { en: "distressing", el: "οδυνηρός", sent: "Circumstances more or less distressing." },
  { en: "drunkenness", el: "μέθη", sent: "Habits of drunkenness." },
  { en: "Dwelling in", el: "κατοικώντας σε", sent: "Dwelling in thoughts of peace." },
  { en: "Equitable", el: "δίκαιος", sent: "Equitable outworking of self." },
  { en: "Erroneous", el: "εσφαλμένος", sent: "Judgment is found erroneous." },
  { en: "fluctuating", el: "κυμαινόμενος", sent: "Fluctuating sensations." },
  { en: "Glorify", el: "δοξάζω", sent: "The vision that you glorify." },
  { en: "Gluttony", el: "λαιμαργία", sent: "Disease as result of gluttony." },
  { en: "gratification", el: "ικανοποίηση", sent: "Fullest measure of gratification." },
  { en: "Groveling", el: "δουλοπρεπής", sent: "Pathway of grovelling thoughts." },
  { en: "hang upon", el: "κρέμομαι από", sent: "Men hang upon his words." },
  { en: "Heartaches", el: "καημοί", sent: "They do not know the heartaches." },
  { en: "Imprison", el: "φυλακίζω", sent: "Thoughts imprison, being base." },
  { en: "indecision", el: "αναποφασιστικότητα", sent: "Thoughts of indecision." },
  { en: "indulged", el: "επιδοθείς", sent: "Even if not physically indulged." },
  { en: "Indulgence", el: "επιείκεια", sent: "Indigence and indulgence." },
  { en: "innumerable", el: "αναρίθμητος", sent: "Innumerable destinies revolve." },
  { en: "insurmountable", el: "αξεπέραστος", sent: "Overcome the apparently insurmountable." },
  { en: "Introspection", el: "ενδοσκόπηση", sent: "Easy investigation by introspection." },
  { en: "isles", el: "νήσοι", sent: "Isles of Blessedness are smiling." },
  { en: "kaleidoscope", el: "καλειδοσκόπιο", sent: "The world is your kaleidoscope." },
  { en: "Latent", el: "λανθάνων", sent: "Development of latent powers." },
  { en: "lofty", el: "υψηλός", sent: "Lofty dreams." },
  { en: "Long-cherished", el: "μακροχρόνια αγαπημένος", sent: "Long-cherished association." },
  { en: "luminous", el: "φωτεινός", sent: "Fixed and luminous centre." },
  { en: "malice", el: "κακία", sent: "Thoughts of malice." },
  { en: "Mellowed", el: "ωριμασμένος", sent: "Softly mellowed like sunset." },
  { en: "molding", el: "πλάθοντας", sent: "Molding and moving force." },
  { en: "Nettles", el: "τσουκνίδες", sent: "Nothing from nettles but nettles." },
  { en: "Nourishing", el: "θρεπτικός", sent: "Are nourished by visions." },
  { en: "offspring", el: "απόγονοι", sent: "Offspring of a deathless Soul." },
  { en: "Oppressor", el: "καταπιεστής", sent: "One is an oppressor." },
  { en: "Persisted in", el: "επέμεινε σε", sent: "Persisted in, be it good or bad." },
  { en: "Pertaining to", el: "σχετικό με", sent: "Truths pertaining to the soul." },
  { en: "pleasantness", el: "ευχαρίστηση", sent: "Circumstances of pleasantness." },
  { en: "poise", el: "ισορροπία", sent: "Exquisite poise of character." },
  { en: "Prey to", el: "βορά σε", sent: "Fall an easy prey to worries." },
  { en: "Propagate", el: "διαδίδω", sent: "Propagate unclean thoughts." },
  { en: "Purification", el: "κάθαρση", sent: "Self-purification." },
  { en: "Realm of", el: "σφαίρα", sent: "Hidden realm of thought." },
  { en: "Reap", el: "θερίζω", sent: "Reap the good results." },
  { en: "Refinement", el: "εκλέπτυνση", sent: "Arts of refinement." },
  { en: "regeneration", el: "αναγέννηση", sent: "Regeneration of the world." },
  { en: "Rendering", el: "αποδίδοντας", sent: "Rendering it crooked." },
  { en: "Retards", el: "επιβραδύνει", sent: "Stubbornly retards efforts." },
  { en: "reverence", el: "ευλάβεια", sent: "They reverence his strength." },
  { en: "Revolting", el: "επαναστατών", sent: "Continually revolting against effect." },
  { en: "Rudiments", el: "βασικές αρχές", sent: "Simplest rudiments of prosperity." },
  { en: "saviors", el: "σωτήρες", sent: "Dreamers are the saviors of the world." },
  { en: "seedlings", el: "σπορόφυτα", sent: "Dreams are seedlings of realities." },
  { en: "sensuality", el: "αισθησιασμός", sent: "Habits of drunkenness and sensuality." },
  { en: "sheltering", el: "προσφέρει καταφύγιο", sent: "Sheltering rock in a storm." },
  { en: "solidifies into", el: "στερεοποιείται σε", sent: "Habit solidifies into circumstance." },
  { en: "Solitary", el: "μοναχικός", sent: "Solitary dreamers." },
  { en: "Spiritual ideal", el: "πνευματικό ιδανικό", sent: "May take form of spiritual ideal." },
  { en: "stainless", el: "άσπιλος", sent: "Stainless beauty." },
  { en: "Steadfastly", el: "σταθερά", sent: "Steadfastly walking the highway." },
  { en: "surges", el: "ορμά", sent: "Humanity surges with passion." },
  { en: "sustained by", el: "συντηρείται από", sent: "Sustained by the invisible." },
  { en: "Thwarted", el: "ματαιωμένος", sent: "Ambitions are thwarted." },
  { en: "tumultuous", el: "ταραχώδης", sent: "Is tumultuous with grief." },
  { en: "undaunted", el: "ατρόμητος", sent: "Undaunted efforts." },
  { en: "undertaking", el: "εγχείρημα", sent: "Fail in any undertaking." },
  { en: "Virtuous", el: "ενάρετος", sent: "Virtuous aspirations." },
  { en: "vocations", el: "κλίσεις", sent: "Sordid vocations." },
  { en: "Voluntarily", el: "εκουσίως", sent: "Voluntarily encountered." },
  { en: "watchfulness", el: "επαγρύπνηση", sent: "Maintained by watchfulness." },
  { en: "Wields", el: "χειρίζεται", sent: "Wields mental powers." },
];

/** Κατηγορία 3 — Ελαφρά (1 άσκηση ανά λέξη) */
export const CAT3: Word[] = [
  { en: "abject", el: "άθλιος", sent: "Remain weak, abject, miserable." },
  { en: "abode", el: "κατοικία", sent: "Sweet and wholesome abode." },
  { en: "Aphorism", el: "αφορισμός", sent: "The aphorism, As a man thinketh." },
  { en: "Artifice", el: "τέχνασμα", sent: "Not a creation by artifice." },
  { en: "Beheld", el: "αντίκρισε", sent: "Buddha beheld the vision." },
  { en: "bestial", el: "κτηνώδης", sent: "Bestial character." },
  { en: "Blessedness", el: "μακαριότητα", sent: "Isles of Blessedness." },
  { en: "Ceaseless", el: "αδιάκοπος", sent: "Ceaseless importunity." },
  { en: "condemnatory", el: "καταδικαστικός", sent: "Condemnatory thoughts." },
  { en: "congenial", el: "συμπαθής", sent: "Uncongenial circumstances." },
  { en: "Consecrated", el: "καθαγιασμένος", sent: "Thought consecrated to search." },
  { en: "cooperators", el: "συνεργάτες", sent: "Oppressor and slave are co-operators." },
  { en: "defiled", el: "μολυσμένος", sent: "Out of defiled mind." },
  { en: "despondency", el: "απελπισία", sent: "Disappointment, despondency." },
  { en: "destitution", el: "εξαθλίωση", sent: "Circumstances of destitution." },
  { en: "Divinity", el: "θεότητα", sent: "Divinity that shapes our ends." },
  { en: "Enervating", el: "εξουθενωτικός", sent: "Enervating habits." },
  { en: "enthroned", el: "ενθρονισμένος", sent: "Ideal enthroned in heart." },
  { en: "ephemeral", el: "εφήμερος", sent: "Ephemeral fancies." },
  { en: "equanimity", el: "ψυχραιμία", sent: "Self-control and equanimity." },
  { en: "faultless", el: "άψογος", sent: "Faultless performance of duty." },
  { en: "garment", el: "ένδυμα", sent: "Inner garment of character." },
  { en: "Garners", el: "συλλέγει", sent: "Garners his own suffering." },
  { en: "Gladdening", el: "που χαροποιεί", sent: "More gladdening truth." },
  { en: "Husbandry", el: "γεωργία", sent: "Sweet and bitter fruitage of husbandry." },
  { en: "ignoble", el: "ανέντιμος", sent: "Ignoble character." },
  { en: "Indolent", el: "οκνηρός", sent: "Indolent, deceptive thoughts." },
  { en: "ineffectual", el: "αναποτελεσματικός", sent: "Crooked, ineffectual, useless." },
  { en: "Inharmonious", el: "δυσαρμονικός", sent: "Inharmonious contours." },
  { en: "Inmost", el: "μύχιος", sent: "Inmost thoughts and desires." },
  { en: "irresolute", el: "αναποφάσιστος", sent: "Irresolute habits." },
  { en: "magnanimous", el: "μεγαλόψυχος", sent: "Honest, magnanimous, virtuous." },
  { en: "Malevolent", el: "κακόβουλος", sent: "Malevolent microbe." },
  { en: "moulder", el: "φθείρεται", sent: "Moulder of character." },
  { en: "Outworking", el: "έκβαση", sent: "Equitable outworking of self." },
  { en: "portals", el: "πύλες", sent: "Portals of heaven." },
  { en: "Possessor", el: "κάτοχος", sent: "Abounding peace to possessor." },
  { en: "reclines", el: "ανακλίνεται", sent: "In bark reclines the Master." },
  { en: "repose", el: "ανάπαυση", sent: "Circumstances of repose and peace." },
  { en: "revile", el: "υβρίζω", sent: "Ceases to whine and revile." },
  { en: "righteously", el: "δίκαια", sent: "Lived righteously." },
  { en: "righteousness", el: "δικαιοσύνη", sent: "Righteousness is the force." },
  { en: "slavish", el: "δουλικός", sent: "Slavish animal indulgence." },
  { en: "sordid", el: "αισχρός", sent: "Sordid vocations." },
  { en: "Unchastened", el: "αχαλίνωτος", sent: "Unchastened desires." },
  { en: "uncleanliness", el: "ακαθαρσία", sent: "Habits of uncleanliness." },
  { en: "Undeviating", el: "αταλάντευτος", sent: "Undeviating in hidden realm." },
  { en: "Unerringly", el: "αλάνθαστα", sent: "May unerringly prove." },
  { en: "Unevolved", el: "μη εξελιγμένος", sent: "Evolving, yet unevolved self." },
  { en: "Unschooled", el: "απαίδευτος", sent: "Unschooled, lacking arts." },
  { en: "vicissitudes", el: "σκαμπανεβάσματα", sent: "Succession of vicissitudes." },
  { en: "Weed-seeds", el: "σπόροι ζιζανίων", sent: "Weed-seeds will fall." },
  { en: "Wielder", el: "χειριστής", sent: "Wielder of mental powers." },
  { en: "Wretchedly", el: "άθλια", sent: "Wretchedly poor." },
  { en: "wretchedness", el: "αθλιότητα", sent: "Extremes of wretchedness." },
];

export const ALL_WORDS: CategorizedWord[] = [
  ...CAT1.map((w) => ({ ...w, cat: 1 as const })),
  ...CAT2.map((w) => ({ ...w, cat: 2 as const })),
  ...CAT3.map((w) => ({ ...w, cat: 3 as const })),
];

export const CATEGORY_TOTALS: Record<Category, number> = {
  1: CAT1.length,
  2: CAT2.length,
  3: CAT3.length,
};

export const CATEGORY_META: Record<Category, { label: string; badge: string; dot: string }> = {
  1: { label: "Έντονα", badge: "bg-[#ff4d2e] text-white", dot: "bg-[#ff4d2e]" },
  2: { label: "Μεσαία", badge: "bg-[#2563eb] text-white", dot: "bg-[#2563eb]" },
  3: { label: "Ελαφρά", badge: "bg-[#10b981] text-white", dot: "bg-[#10b981]" },
};

export const LESSON_TITLES = [
  "Σκέψη & Χαρακτήρας",
  "Περιστάσεις & Νόμος",
  "Σώμα & Νους",
  "Σκοπός & Επίτευξη",
  "Όνειρα & Πραγματικότητα",
  "Κακία, Αρετή & Γαλήνη",
  "Πειρασμοί & Έλεγχος",
  "Ευημερία & Επιτυχία",
  "Οράματα & Ιδανικά",
  "Καλλιέργεια του Νου",
  "Δύναμη & Ευθύνη",
  "Φώτιση & Ελευθερία",
] as const;

/** Πόσες λέξεις κάθε κατηγορίας μπαίνουν σε κάθε ένα από τα 12 μαθήματα. */
export const LESSON_SPLIT: Record<Category, number[]> = {
  1: [9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8],
  2: [8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7],
  3: [5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4],
};
